export const technologies = [
    "Html",
    "Css",
    "Javascript",
    "jQuery",
    "Scss",
    "Bootstrap",
    "Tailwind",
    "reactJs",
    "nextJs",
    "Git",
    "Github",
    "NodeJs",
    "MongoDb",
    "GraphQl",
    "ExpressJs",
    "Php",
    "Laravel",
    "Wordpress",
    "Netlify",
    "Firebase",
    "Vercel",
    "Heroku",
    "MySql",
    "AdobeXd",
    "Figma",
];


export const categories = [
    "Programming",
    "Book",
    "General Topics",
    "Translated Articles",
    "Web Development",
    "Frontend",
    "Backend",
    "UI/UX",
    "Religion",
    "Science",
    "notes",
    "politics",
    "Html",
    "Css",
    "Javascript",
    "jQuery",
    "Scss",
    "Bootstrap",
    "Tailwind",
    "reactJs",
    "nextJs",
    "Git",
    "Github",
    "NodeJs",
    "MongoDb",
    "GraphQl",
    "ExpressJs",
    "Php",
    "Laravel",
    "Wordpress",
    "Netlify",
    "Firebase",
    "Vercel",
    "Heroku",
    "MySql",
    "AdobeXd",
    "Figma",
    "uncategorized",
];